name: ci-maven
on:
  pull_request:
    branches: [ "main", "develop"]
  push:
    branches: ["*"]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [17, 21]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4    
      
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: maven

      - name: Test with Maven
        run: mvn clean -U install
