name: ci-codecov

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v2
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
